trigger: none

pool:
  vmImage: macos-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: Common.Pipelines.Templates
      ref: refs/tags/v1.0.0

variables:
- group: sandbox-secrets

stages:
- stage: 
  displayName: 'Build stage'
  jobs:
    - template: ./jobs/job-dotnet-build-sign-aab.yml@templates
      parameters:
        projectName: Demo.Maui.DevOps
        applicationId: com.companyname.demo.maui.devops
        keystoreCert:
          file: 'sandbox_keystore.jks'
          filePassword: $(keystore.password)
          alias: $(key.alias)
          aliasPassword: $(key.password)
   
- stage: 
  displayName: 'Distribute stage'
  jobs:
    - template: ./deployments/deployment-app-center.yml@templates
      parameters:
        environment: prp
        appSlug: Azure-DevOps-Demo/Demo-MAUI-Android
        app: drop/app-signed.aab
        destinationGroupIds: 1fe21f1a-371e-4f98-b5c7-8deff1c97614